### ISSUE TITLE
Enable transparent huge pages in kernel

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#132]
Some packages know how to use these for a performance improvement. Packages that don't pay no perf penalty

**Comment by jonesmz** [comment]
See upstream report https://github.com/raspberrypi/linux/issues/4687

**Comment by samip5** [comment]
> See upstream report [raspberrypi/linux#4687](https://github.com/raspberrypi/linux/issues/4687)
Does that mean that we cannot enable it in our build?

**Comment by jonesmz** [comment]
We can. Its just another entry in config/kernel.d
