### ISSUE TITLE
Running pychroot messes up cgroups on systemd hosts

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#14]
If we make an ebuild to allow portage to install the project, we'll want to have a USE flag to switch between using pychroot or systemd-nspawnd, to avoid screwing up systemd systems.

Or a wrapper script that detects the chroot tool based on the currently running init system or an environment variable.

**Comment by samip5** [comment]
Hmm, interesting. Mine is running systemd but no such issues. Is your host system Gentoo too?

**Comment by perkinslr** [comment]
Probably need to abstract the chroot command to a script, since the order of options changes between the two.

**Comment by jonesmz** [comment]
> Hmm, interesting. Mine is running systemd but no such issues. Is your host system Gentoo too?

Yes, it is.

It's not clear to me exactly what messed it up, but I have a few hundred thousand journal entries complaining that systemd couldn't manage cgroups, and ssh stopped working :-)

**Comment by perkinslr** [comment]
Might the lack of xattr support in qemu be a contributing factor?

**Comment by jonesmz** [comment]
I can't say that it isn't possible, but I would be pretty confused how the two would interact like that.

**Comment by perkinslr** [comment]
pychroot pulls some cgroup/namespace magic to get sockets, symlinks, and other things from the host environment passed into the chroot in a transparent fashion.  I would not be surprised if some of those sockets had xattrs which qemu then broke.

**Comment by perkinslr** [comment]
There is now a wrapper script that uses `CHROOT_CMD` (default `pychroot` or `systemd-nspawn`).  Autodetecting systemd would be good though...
