### ISSUE TITLE
jenkins: Set up git reference repository per agent for each git repository used in a build

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#146]
The purpose of doing this would be to reduce the amount of git traffic necessary to build.

I've observed github doing fairly aggressive rate limiting in the past for build servers, and caching the repository's chunks in a reference repo on the local disk was very helpful for this.

**Comment by samip5** [comment]
Which has own problema from limited storage on the builders.

**Comment by jonesmz** [comment]
I suspect that a git repo cache would be so small that it wouldn't really be noticable.

The purpose is just to avoid hitting the git ratelimiting, which deals with transactions in addition to overall bandwidth. It's the transaction limit i'm concerned about.

**Comment by jonesmz** [comment]
Implemented
