### ISSUE TITLE
build script redownloading stage3 every run

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#149]
Locally, my build script is re-downloading the stage3 every time.
Something to do with the cache timelimit?

**Comment by samip5** [comment]
Which branch?

**Comment by jonesmz** [comment]
Master, jenkins2

**Comment by samip5** [comment]
Take the downloadstage3 from alpha9.1 branch and try that

**Comment by jonesmz** [comment]
Theoretically this is now fixed in latest jenkins-aws branch.
