### ISSUE TITLE
Request To Activate Wiki

### ISSUE THREAD

**Issue by jlpoolen** [GenPi64/Build.Dist#194]
Logan,

Would it be possible to activate the wiki for the Build.Dist project?

I have some interesting data about the builds after parsing the emerge log that I'd like to share and get some input on and a wiki would be an excellent way to collaborate.

**Comment by jlpoolen** [comment]
For instance, for run 42 of January 28, the "Lite" process, I have entries relating to the ncurses package:

    emergedb=> select line, to_timestamp(epoch) as "Date",
    emerge_batch_id, code, action
    from emerge_event
    where package_name like '%ncurses%'
    and emerge_batch_id in (
       select id
       from emerge_batch
       where jenkins_cat_id = 1
    )
    order by id;
     line |          Date          | emerge_batch_id | code |       action
    ------+------------------------+-----------------+------+---------------------
       44 | 2023-01-28 22:32:29-08 |               3 | >>>  | start
       85 | 2023-01-28 22:33:10-08 |               3 | ===  | compiling-packaging
      248 | 2023-01-28 22:38:04-08 |               3 | >>>  | autoclean
      249 | 2023-01-28 22:38:04-08 |               3 | ===  | unmerging
      250 | 2023-01-28 22:38:09-08 |               3 | >>>  | unmerge completed
      251 | 2023-01-28 22:38:13-08 |               3 | ===  | Post-Build cleaning
      252 | 2023-01-28 22:38:13-08 |               3 | :::  | completed
     1837 | 2023-01-28 23:39:13-08 |               5 | >>>  | start
     1895 | 2023-01-28 23:39:53-08 |               5 | ===  | compiling-packaging
     2208 | 2023-01-28 23:47:44-08 |               5 | >>>  | autoclean
     2209 | 2023-01-28 23:47:44-08 |               5 | ===  | unmerging
     2210 | 2023-01-28 23:47:48-08 |               5 | >>>  | unmerge completed
     2211 | 2023-01-28 23:47:52-08 |               5 | ===  | Post-Build cleaning
     2212 | 2023-01-28 23:47:52-08 |               5 | :::  | completed
     4441 | 2023-01-29 03:44:49-08 |               6 | >>>  | start
     4499 | 2023-01-29 03:45:30-08 |               6 | ===  | compiling-packaging
     4812 | 2023-01-29 03:52:33-08 |               6 | >>>  | autoclean
     4813 | 2023-01-29 03:52:33-08 |               6 | ===  | unmerging
     4814 | 2023-01-29 03:52:37-08 |               6 | >>>  | unmerge completed
     4815 | 2023-01-29 03:52:40-08 |               6 | ===  | Post-Build cleaning
     4816 | 2023-01-29 03:52:40-08 |               6 | :::  | completed
    (21 rows)

and the 

    emergedb=> --
    -- What are the emerge batchs for the Lite build?
    --
    select id, line
    from emerge_batch
    where jenkins_cat_id = 1;
     id | line
    ----+------
      1 |    2
      2 |   25
      3 |   41
      4 | 1822
      5 | 1833
      6 | 4437
      7 | 7055
      8 | 7060
      9 | 7916
     10 | 7920
     11 | 7926
     12 | 7933
    (12 rows)

    emergedb=>

It would be helpful to solicit the rational for the 12 emerges to help newcomers to the project understand what the order of processing is and why.

(I'll probably digest the entire emerge log so I can output the entire line being referenced.)

**Comment by samip5** [comment]
The wiki is active already though? or which one do you refer to?

**Comment by jlpoolen** [comment]
I thought github offers wikis in a project and that it appears along the top line:

![firefox_2023-02-02_21-02-26](https://user-images.githubusercontent.com/227313/216516880-12580607-58c2-4604-9bd3-0cf1cbf2e596.png)

Here's an example from another Github project:

![firefox_2023-02-02_21-04-46](https://user-images.githubusercontent.com/227313/216517038-71aac395-beb0-47e1-82e7-f68543ba9b15.png)

**Comment by samip5** [comment]
> I thought github offers wikis in a project and that it appears along the top line:
> 
> ![firefox_2023-02-02_21-02-26](https://user-images.githubusercontent.com/227313/216516880-12580607-58c2-4604-9bd3-0cf1cbf2e596.png)
> 
> Here's an example from another Github project:
> 
> ![firefox_2023-02-02_21-04-46](https://user-images.githubusercontent.com/227313/216517038-71aac395-beb0-47e1-82e7-f68543ba9b15.png)

<img width="928" alt="Screenshot 2023-02-03 at 7 12 20" src="https://user-images.githubusercontent.com/1703002/216518107-690d58de-04bf-43d9-b6f1-c11ab20340ef.png">
Yes? :D

**Comment by jlpoolen** [comment]
While your screen shows a wiki, mine still does not.  So perhaps there is a wiki, but the permission are such that I cannot access it.
![2023-02-02_21-17](https://user-images.githubusercontent.com/227313/216518578-51ba337f-0186-439f-b081-62558469c032.png)

**Comment by samip5** [comment]
> While your screen shows a wiki, mine still does not. So perhaps there is a wiki, but the permission are such that I cannot access it.

I made a one wiki page, so check if you can access it https://github.com/GenPi64/Build.Dist/wiki

**Comment by jlpoolen** [comment]
I can see a heading "wiki" and I can visit the page.  But there is no facility for me to edit the page or contribute.  Here is a screen shot at 8:19 AM PST, February 4, 2023.  It appears the only option I have is to download a copy of the wiki using the button at the bottom right.
![image](https://user-images.githubusercontent.com/227313/216778112-e2c48977-0977-4055-9edf-aa3f1613aecf.png)

For reference, here is a page from the Moonfire-nvr project where I am able to participate in the wiki.  It looks like the configuration of permissions is the cause here for the discrepancy and places this matter back to Logan.

![image](https://user-images.githubusercontent.com/227313/216778269-c2649509-8926-47cf-a0ae-23cc55c698d6.png)

**Comment by samip5** [comment]
Okay and only person that can do something about is is Logan aka @perkinslr.

**Comment by jlpoolen** [comment]
Thank you for trying.

**Comment by jonesmz** [comment]
@perkinslr

**Comment by jlpoolen** [comment]
@perkinslr

**Comment by maffblaster** [comment]
The wiki should be editable now by the community. Please let me know if this is not the case.
