### ISSUE TITLE
Use dash as /bin/sh

### ISSUE THREAD

**Issue by equwal** [GenPi64/Build.Dist#203]
Kind of an obvious decision over bash in my view for an embedded system to use a performance oriented default POSIX shell (can still use bash for interactive logins).

**Comment by samip5** [comment]
@equwal I would love to hear some actual reasons, eg cons/pros kinda thing about this one?

**Comment by equwal** [comment]
Dash is allegedly 6x faster than bash.
Dash is POSIX like bash which is nice.
It only adds a tiny amount of data.

Dash is the default in OpenWRT, Alpine, Busybox...etc. because it is a good default shell to symlink `/bin/sh` to.

**Comment by jonesmz** [comment]
One of the design objectives is to keep the "normal" image as close to baseline gentoo as can be practically managed.

But if you wanted to submit a PR that built a variant of the images with dash instead of bash, i'd be happy to review it for you.
