### ISSUE TITLE
Add post image build step that shrinks the filesystem and truncs the image file

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#41]
Currently for the "lite" image, the file itself is 8gb, but it doesn't contain that much data internally.

A generalized approach to this might be

1) Mount the image file on the loopback
2) Run btrfs dedup
3) Determine actual storage used with something like btrfs fi df, or similar
4) Btrfs resize to actual-size + 10%
5) Unmount the image file
6) fixup the partition table using fdisk / gdisk
7) trunc the image to the new size.

**Comment by perkinslr** [comment]
Done.
