### ISSUE TITLE
Add initramfs

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#43]
Useful for recovery tools in case of boot failure. Instead of just a kernel panic.

**Comment by samip5** [comment]
Or for full system encryption.

**Comment by necrose99** [comment]
I haven't qualms,  however dracut plus pushing dtb or device trees into intramfs or improving tools in the pkg ... of busybox in intramfs

**Comment by perkinslr** [comment]
The current Pi firmware supports specifying initramfs via config.txt, no need to embed it in the kernel directly.  And no need to calculate addresses a la initrd.
