### ISSUE TITLE
Add nodiratime flag to / partition

### ISSUE THREAD

**Issue by hrk** [GenPi64/Build.Dist#50]
Same rationale as #42

**Comment by perkinslr** [comment]
Note that turning on noatime implicitly means that nodiratime is enabled as well.  So I don't think setting this flag explicitly is warranted.  The one related flag we might consider is `relatime`, which updates `atime` only if the last `atime` is earlier than the `mtime` (which has implications for programs that track "new" files).  Even that I think is not worth setting, as anyone using one of those programs is likey to want to customize their mount flags regardless.

**Comment by hrk** [comment]
I didn't know that noatime included nodiratime. Time to clean up /etc/fstab on my old boxes then... :-)

**Comment by perkinslr** [comment]
No worries.  Check `man mount` for details.

**Comment by hrk** [comment]
Well, I've been using it way before 2007 ( https://lwn.net/Articles/244941/ ) and never checked the docs again...
