### ISSUE TITLE
Problems with crudini

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#54]
Crudini is creating an invalid config.txt file.

1) Inserting DEFAULT at the top of the file. Raspberry Pi OS's config.txt does not do that.
2) Spaces inserted before and after = symbols in any newly added key=val line

See https://github.com/GenPi64/Build.Dist/pull/55 for an incomplete attempt at a fix.

**Comment by jonesmz** [comment]
Found the problem.

Spaces being injected before and after the = symbol in the ini file.

https://github.com/GenPi64/Build.Dist/pull/55/files is an attempted fix.

**Comment by perkinslr** [comment]
See upstream bug https://github.com/pixelb/crudini/issues/33
The issue isn't with `crudini`, it's actually upstream to `crudini` in `dev-python/iniparse`.  Fixing the whitespace around = is trivial, just reflect into `iniparse` to change the default separator (I'll open a PR for that shortly).  

I'll have to poke a bit more to solve the `DEFAULT` issue, but it should be pretty simple too.

**Comment by perkinslr** [comment]
The default section issue is because we are explicitly saying `DEFAULT` as the section, which makes it treat it as a proper section instead of an implicit section.  Replace it with an empty string and that problem is solved.
