### ISSUE TITLE
Configure X on the desktop profile

### ISSUE THREAD

**Issue by perkinslr** [GenPi64/Build.Dist#68]
Currently `xdm` dumps you into an unconfigured `xsm` instance, which doesn't let you do anything useful.  `.xinitrc` needs to be created and configured to launch `xfce4` instead.

**Comment by k9spud** [comment]
On my Sakaki system, there exists a file `/etc/env.d/90xsession` that contains:```XSESSION="Xfce4"```
This file is not owned by any package (verified by qfile), and does not exist in the alpha7 image. I'm guessing it must've been created by Sakaki's one-time run scripts or something. 

Anyway, that environment variable, XSESSION, seems to be what causes /etc/X11/chooser.sh on alpha7 to fail to output "/etc/X11/Sessions/Xfce4" the way it should and does on my Sakaki system.
