### ISSUE TITLE
if stage3 auto-download is interrupted, later runs will fail.

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#8]
We can additionally download the digests file (e.g. http://distfiles.gentoo.org/releases/arm64/autobuilds/20201228T003515Z/stage3-arm64-20201228T003515Z.tar.xz.DIGESTS) and verify the downloaded stage3 both after downloading, as well as on a second run, triggering a new download if the digest fails.

**Comment by perkinslr** [comment]
I don't have it trigger a new download, since someone on a slow/metered connection may want to manually resume the download instead, but it now checks the manifest and halts if it doesn't match.
