### ISSUE TITLE
Why delete /var/db/repos from the image file?

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#84]
in parsers/strip/strip we're deleting everything under /var/db/repos/, which would include both the gentoo tree, as well as the genpi64 overlay.

Why would we want to remove that from the image file?

**Comment by perkinslr** [comment]
2 reasons.  First, it lets the image shrink considerably.  If the image is at all old, the current portage tree is likely to be sufficiently out of date to need a nearly full update anyway, and if you are downloading it to a gentoo system, you can copy your local tree in far faster than you can copy a larger image.  Also, the current commit pinning leaves `::gentoo` in a state that breaks `emerge --sync`, so clearing it out is necessary.  

If we get our own github mirror of `::gentoo`, or some other solution to that issue, it would be worth revisiting this.
