### ISSUE TITLE
Default to storing auto-downloaded stage3 with PROJECT_DIR

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#9]

**Comment by samip5** [comment]
Agreed, that should be better.

**Comment by perkinslr** [comment]
Probably should use an env variable to determine where to put it.  `PROJECT_DIR` may well get purged after a run, while the stage3 should probably linger.  But I agree, defaulting to something like `PROJECT_DIR/stage3/` would make sense.
