### ISSUE TITLE
Change the kernel default cpufrequency governer from powersave to conservative

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#93]
Better than being locked to 600mhz by default.

**Comment by samip5** [comment]
Is this not handled by the rpi-on-demand service?

**Comment by jonesmz** [comment]
Out of the box the kernel should have sensible defaults.

The conservative governor is suitable for all but the most intense workloads, and doesn't require running the on demand service (even though its not really a service as much as it is a one-off script to change the frequency governor).

I'd rather not require a service to run at boot just to make my board scale the CPU to meet demand, personally.
