### ISSUE TITLE
Missing v3d entry in portage make.conf VIDEO_CARDS

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#95]
The graphics driver on rpi4 is v3d.

**Comment by samip5** [comment]
Keep in mind that the image needs to support RPi4 AND RPi3.

**Comment by jonesmz** [comment]
Mesa should be smart enough to automatically select the correct driver. The only cost for rpi3 will be a bit of extra storage space used.

**Comment by jonesmz** [comment]
Fixed by https://github.com/GenPi64/Build.Dist/commit/8259189d06a23ee3aefe1641f65b8e013372845f

**Comment by samip5** [comment]
@jonesmz This would have been closed automatically by my commit when merged to master. No need to actually close it manually.
